//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskCrypto.Resource.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestTaskCrypto.Resource.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1 дн.
        /// </summary>
        public static string _1_day {
            get {
                return ResourceManager.GetString("1 day", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1 міс.
        /// </summary>
        public static string _1_Mon {
            get {
                return ResourceManager.GetString("1 Mon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1 рік.
        /// </summary>
        public static string _1_Year {
            get {
                return ResourceManager.GetString("1 Year", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 6 міс.
        /// </summary>
        public static string _6_Mon {
            get {
                return ResourceManager.GetString("6 Mon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7 дн.
        /// </summary>
        public static string _7_Days {
            get {
                return ResourceManager.GetString("7 Days", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Монета яку купляти.
        /// </summary>
        public static string coin_to_buy {
            get {
                return ResourceManager.GetString("coin to buy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Інформація про монету.
        /// </summary>
        public static string CoinInformationPage {
            get {
                return ResourceManager.GetString("CoinInformationPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Конвертатор валют.
        /// </summary>
        public static string Currency_converter {
            get {
                return ResourceManager.GetString("Currency converter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Темна.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Оформлення.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Деталі.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Англійська.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Загальне.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Головна сторінка.
        /// </summary>
        public static string Home_page {
            get {
                return ResourceManager.GetString("Home_page", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Мова.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Світла.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Локалізація.
        /// </summary>
        public static string localization {
            get {
                return ResourceManager.GetString("localization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Основна сторінка.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ринки де можна купити валюту.
        /// </summary>
        public static string Markets_where_you_can_buy_currency {
            get {
                return ResourceManager.GetString("Markets where you can buy currency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Назва ринку.
        /// </summary>
        public static string Name_of_the_market {
            get {
                return ResourceManager.GetString("Name of the market", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Кількітсь монет.
        /// </summary>
        public static string Number_of_coins {
            get {
                return ResourceManager.GetString("Number of coins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ціна.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Калькулятор Ціни.
        /// </summary>
        public static string Price_calculator {
            get {
                return ResourceManager.GetString("Price calculator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Програма.
        /// </summary>
        public static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сайт програми.
        /// </summary>
        public static string Program_website {
            get {
                return ResourceManager.GetString("Program_website", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string rating {
            get {
                return ResourceManager.GetString("rating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Для зміни мови перезагрузіть програму.
        /// </summary>
        public static string restart_Program {
            get {
                return ResourceManager.GetString("restart Program", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Повернутися на головну.
        /// </summary>
        public static string Return_to_the_main_page {
            get {
                return ResourceManager.GetString("Return to the main page", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сайт.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Монета за яку купляти.
        /// </summary>
        public static string the_coin_to_buy_with {
            get {
                return ResourceManager.GetString("the coin to buy with", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Кількість рядків 10.
        /// </summary>
        public static string The_number_of_lines_is_10 {
            get {
                return ResourceManager.GetString("The number of lines is 10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Теми.
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Українська.
        /// </summary>
        public static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Обєм за 24 години.
        /// </summary>
        public static string Volume_in_24_hours {
            get {
                return ResourceManager.GetString("Volume in 24 hours", resourceCulture);
            }
        }
    }
}
